name: Run tests with coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  validate_commit:
    name: Validate commit
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.*'

      - uses: extractions/setup-just@v3

      - name: Check Format
        run: gofmt -d ./

      - name: Verify dependencies
        run: go mod verify

      - name: Install dependencies
        run: go mod vendor

      - name: Run go vet
        run: go vet ./...

      - name: Build
        run: go build -v ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v9

      - name: Setup test environment
        run: just up

      - name: Run unit tests
        run: go test -v ./... -short -timeout 5m -kubeconfig-cmd "kind get kubeconfig" -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

      - name: Check test coverage
        id: coverage
        uses: vladopajic/go-test-coverage@v2
        continue-on-error: true # Should fail after coverage comment is posted
        with:
          config: .testcoverage.yaml

      - name: Post coverage report
        uses: thollander/actions-comment-pull-request@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-tag: coverage-report
          message: |
            go-test-coverage report:
            ```${{ fromJSON(steps.coverage.outputs.report) }}```

      - name: Finally check coverage
        if: false # Disable since tests are not implemented yet
        # if: steps.coverage.outcome == 'failure'
        shell: bash
        run: echo "coverage check failed" && exit 1

      - name: Build binary for integration tests
        run: go build -o tests/bin/kubectl-arcane main.go

      - name: Run integration tests
        run: go test -v ./tests/... -count=1 -kubeconfig-cmd "kind get kubeconfig" -timeout 5m

      - name: Get logs from application pods
        if: always()
        run: |
          kubectl describe pods --namespace default || true

  validate_dockerfile:
    name: Validate dockerfile
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@v3.5.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get project version
        uses: SneaksAndData/github-actions/generate_version@v0.1.11
        id: version

      - name: Get build number
        shell: bash
        id: buildnumber
        run: |
          dt=$(date +'%Y%m%d%H%M%S')
          echo "result=$dt" >> "$GITHUB_OUTPUT"

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},value=${{steps.version.outputs.version}}
          flavor:
            latest=false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1
        with:
          use: true
          platforms: linux/arm64,linux/amd64

      - name: Build docker image (validate Dockerfile)
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          build-args: |
            APPVERSION=${{ steps.version.outputs.version }}
            BUILDNUMBER=${{ steps.buildnumber.outputs.result }}
          file: .container/Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64,linux/amd64
